# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  zanshinsdk_jobs:
    strategy:
      matrix:
        python-version: [ 3.7 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    name: Test and Coverage
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: snok/install-poetry@v1.3.2
        with:
          version: 1.5.1
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: poetry install

      - name: Unit test
        run: |
          poetry run python -m unittest discover -v
