name: Upload Python Package

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine pandoc
          python setup.py develop

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          sed -i 's/__PACKAGE_VERSION__/${{ github.event.release.tag_name }}/g' zanshinsdk/version.py setup.py 
          make pypi
